# Generated by Django 5.0 on 2023-12-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
